### ISSUE TITLE
Not able to run in Android Studio getting error

### ISSUE THREAD

**Issue by i-sourabh** [dhis2/dhis2-android-trackercapture#56]
Hi,
I have done all the steps mentioned by you but still i am not able to run the project , getting following error:

Error:Configuration with name 'default' not found.

Please help

**Comment by andy003** [comment]
abybody can help?

**Comment by russnes** [comment]
Can you try to rename the folders from dhis2-android-sdk-master to dhis2-android-sdk, and also rename dhis2-android-trackercapture-master to dhis2-android-trackercapture. 

I tested it myself on my computer and it solved the problem. Please let me know if it works.

**Comment by i-sourabh** [comment]
Hey simernes Tahnk you so much for the reply,
I have renamed both folders and kept them in a single folder also, now when I try to import the project dhis2-android-trackercapture  at first glance everything seems to be ok but when i clicked on the java files one by one errors  coming to start. Error:Configuration with name 'default' not found has gone but now there are many other errors , common error is import org.hisp.dhis.android.sdk.R;  I think it is not picking up the SDK path ,Below are the issues:

Error:E:\TRackercapture\dhis2-android-sdk\app\src\main\java\org\hisp\dhis\android\sdk\controllers\datavalues\DataValueSender.java:47: The import org.hisp.dhis.android.sdk.persistence.models.Enrollment$Table cannot be resolved

E:\TRackercapture\dhis2-android-trackercapture\app\src\main\java\org\hisp\dhis\android\trackercapture\MainActivity.java
Error:(37, 45) error: cannot find symbol class DhisController
Error:(38, 45) error: cannot find symbol class DhisService
Error:(39, 45) error: cannot find symbol class LoadingController
Error:(40, 45) error: cannot find symbol class PeriodicSynchronizerController
Error:(42, 57) error: cannot find symbol class ResourceType
Error:(43, 47) error: package org.hisp.dhis.android.sdk.ui.activities does not exist
Error:(44, 47) error: package org.hisp.dhis.android.sdk.ui.activities does not exist
Error:(45, 54) error: package org.hisp.dhis.android.sdk.ui.fragments.loading does not exist
Error:(46, 39) error: cannot find symbol class UiUtils
Error:(50, 64) error: cannot find symbol class INavigationHandler
Error:(52, 13) error: cannot find symbol class OnBackPressedListener
Error:(134, 40) error: cannot find symbol class OnBackPressedListener
E:\TRackercapture\dhis2-android-trackercapture\app\src\main\java\org\hisp\dhis\android\trackercapture\fragments\enrollment\EnrollmentFragment.java
Error:(58, 45) error: cannot find symbol class DhisService
Error:(59, 47) error: package org.hisp.dhis.android.sdk.ui.activities does not exist
Error:(60, 47) error: package org.hisp.dhis.android.sdk.ui.activities does not exist
Error:(62, 56) error: package org.hisp.dhis.android.sdk.ui.fragments.dataentry does not exist
Error:(63, 56) error: package org.hisp.dhis.android.sdk.ui.fragments.dataentry does not exist
Error:(64, 37) error: package org.hisp.dhis.android.sdk.job does not exist
Error:(65, 37) error: package org.hisp.dhis.android.sdk.job does not exist
Error:(66, 41) error: package org.hisp.dhis.android.sdk.network does not exist
Error:(70, 57) error: cannot find symbol class ResourceType
Error:(71, 45) error: cannot find symbol class GpsController
Error:(72, 39) error: cannot find symbol class UiUtils
Error:(74, 45) error: package org.hisp.dhis.android.sdk.ui.adapters does not exist
Error:(76, 45) error: cannot find symbol class DhisController
Error:(91, 9) error: cannot find symbol class OnBackPressedListener
Error:(110, 13) error: cannot find symbol class DataValueAdapter
Error:(112, 13) error: cannot find symbol class INavigationHandler
Error:(398, 41) error: cannot find symbol class RowValueChangedEvent
E:\TRackercapture\dhis2-android-trackercapture\app\src\main\java\org\hisp\dhis\android\trackercapture\fragments\enrollment\EnrollmentFragmentForm.java
Error:(8, 60) error: package org.hisp.dhis.android.sdk.ui.adapters.rows.dataentry does not exist
Error:(9, 60) error: package org.hisp.dhis.android.sdk.ui.adapters.rows.dataentry does not exist
Error:(28, 18) error: cannot find symbol class IndicatorRow
Error:(29, 18) error: cannot find symbol class DataEntryRow
Error:(31, 17) error: cannot find symbol class DataEntryRow
Error:(35, 39) error: cannot find symbol class DataEntryRow
E:\TRackercapture\dhis2-android-trackercapture\app\src\main\java\org\hisp\dhis\android\trackercapture\fragments\enrollment\EnrollmentFragmentQuery.java
Error:(5, 53) error: package org.hisp.dhis.android.sdk.controllers.tracker does not exist
Error:(17, 60) error: package org.hisp.dhis.android.sdk.ui.adapters.rows.dataentry does not exist
Error:(18, 60) error: package org.hisp.dhis.android.sdk.ui.adapters.rows.dataentry does not exist
Error:(19, 60) error: package org.hisp.dhis.android.sdk.ui.adapters.rows.dataentry does not exist
Error:(20, 60) error: package org.hisp.dhis.android.sdk.ui.adapters.rows.dataentry does not exist
Error:(21, 60) error: package org.hisp.dhis.android.sdk.ui.adapters.rows.dataentry does not exist
Error:(22, 60) error: package org.hisp.dhis.android.sdk.ui.adapters.rows.dataentry does not exist
Error:(23, 60) error: package org.hisp.dhis.android.sdk.ui.adapters.rows.dataentry does not exist
Error:(117, 12) error: cannot find symbol class DataEntryRow
E:\TRackercapture\dhis2-android-trackercapture\app\src\main\java\org\hisp\dhis\android\trackercapture\fragments\enrollmentdate\EnrollmentDateFragment.java
Error:(26, 45) error: cannot find symbol class DhisService
Error:(27, 47) error: package org.hisp.dhis.android.sdk.ui.activities does not exist
Error:(28, 47) error: package org.hisp.dhis.android.sdk.ui.activities does not exist
Error:(29, 45) error: cannot find symbol class DhisController
Error:(30, 53) error: package org.hisp.dhis.android.sdk.controllers.tracker does not exist
Error:(31, 56) error: package org.hisp.dhis.android.sdk.ui.fragments.dataentry does not exist
Error:(32, 37) error: package org.hisp.dhis.android.sdk.job does not exist
Error:(33, 37) error: package org.hisp.dhis.android.sdk.job does not exist
Error:(34, 41) error: package org.hisp.dhis.android.sdk.network does not exist
Error:(37, 57) error: cannot find symbol class ResourceType
Error:(38, 45) error: package org.hisp.dhis.android.sdk.ui.adapters does not exist
Error:(39, 60) error: package org.hisp.dhis.android.sdk.ui.adapters.rows.dataentry does not exist
Error:(40, 39) error: cannot find symbol class UiUtils
Error:(54, 65) error: cannot find symbol class OnBackPressedListener
Error:(60, 13) error: cannot find symbol class INavigationHandler
Error:(67, 13) error: cannot find symbol class DataValueAdapter
Error:(68, 18) error: cannot find symbol class DataEntryRow
Error:(427, 41) error: cannot find symbol class RowValueChangedEvent
E:\TRackercapture\dhis2-android-trackercapture\app\src\main\java\org\hisp\dhis\android\trackercapture\ui\adapters\ProgramStageAdapter.java
Error:(33, 45) error: package org.hisp.dhis.android.sdk.ui.adapters does not exist
Error:(41, 48) error: cannot find symbol class AbsAdapter
E:\TRackercapture\dhis2-android-trackercapture\app\src\main\java\org\hisp\dhis\android\trackercapture\ui\adapters\ProgramAdapter.java
Error:(36, 45) error: package org.hisp.dhis.android.sdk.ui.adapters does not exist
Error:(40, 43) error: cannot find symbol class AbsAdapter
E:\TRackercapture\dhis2-android-trackercapture\app\src\main\java\org\hisp\dhis\android\trackercapture\fragments\programoverview\ProgramOverviewFragment.java
Error:(62, 47) error: package org.hisp.dhis.android.sdk.ui.activities does not exist
Error:(63, 45) error: cannot find symbol class DhisController
Error:(64, 53) error: package org.hisp.dhis.android.sdk.controllers.tracker does not exist
Error:(66, 55) error: package org.hisp.dhis.android.sdk.ui.fragments.settings does not exist
Error:(67, 56) error: package org.hisp.dhis.android.sdk.ui.fragments.dataentry does not exist
Error:(82, 42) error: package org.hisp.dhis.android.sdk.ui.views does not exist
Error:(83, 42) error: package org.hisp.dhis.android.sdk.ui.views does not exist
Error:(84, 39) error: cannot find symbol class UiUtils
Error:(90, 44) error: package org.hisp.dhis.android.sdk.ui.dialogs does not exist
Error:(109, 30) error: package ProgramDialogFragment does not exist
Error:(138, 13) error: cannot find symbol class FloatingActionButton
Error:(160, 13) error: cannot find symbol class INavigationHandler
E:\TRackercapture\dhis2-android-trackercapture\app\src\main\java\org\hisp\dhis\android\trackercapture\fragments\programoverview\ProgramOverviewFragmentQuery.java
Error:(31, 53) error: package org.hisp.dhis.android.sdk.controllers.tracker does not exist
E:\TRackercapture\dhis2-android-trackercapture\app\src\main\java\org\hisp\dhis\android\trackercapture\ui\adapters\TrackedEntityInstanceAdapter.java
Error:(11, 45) error: package org.hisp.dhis.android.sdk.ui.adapters does not exist
Error:(12, 57) error: package org.hisp.dhis.android.sdk.ui.adapters.rows.events does not exist
Error:(13, 57) error: package org.hisp.dhis.android.sdk.ui.adapters.rows.events does not exist
Error:(26, 51) error: cannot find symbol class AbsAdapter
Error:(26, 62) error: cannot find symbol class EventRow
E:\TRackercapture\dhis2-android-trackercapture\app\src\main\java\org\hisp\dhis\android\trackercapture\fragments\programoverview\registerrelationshipdialogfragment\RegisterRelationshipDialogFragment.java
Error:(59, 45) error: cannot find symbol class DhisController
Error:(60, 53) error: package org.hisp.dhis.android.sdk.controllers.tracker does not exist
Error:(72, 50) error: package org.hisp.dhis.android.sdk.ui.adapters.rows does not exist
Error:(73, 44) error: package org.hisp.dhis.android.sdk.ui.dialogs does not exist
Error:(74, 42) error: package org.hisp.dhis.android.sdk.ui.views does not exist
Error:(75, 42) error: package org.hisp.dhis.android.sdk.ui.views does not exist
Error:(76, 39) error: cannot find symbol class UiUtils
Error:(84, 138) error: package AutoCompleteDialogFragment does not exist
Error:(91, 13) error: cannot find symbol class CardTextViewButton
Error:(95, 13) error: cannot find symbol class FontTextView
E:\TRackercapture\dhis2-android-trackercapture\app\src\main\java\org\hisp\dhis\android\trackercapture\ui\adapters\RelationshipTypeAdapter.java
Error:(36, 45) error: package org.hisp.dhis.android.sdk.ui.adapters does not exist
Error:(40, 52) error: cannot find symbol class AbsAdapter
E:\TRackercapture\dhis2-android-trackercapture\app\src\main\java\org\hisp\dhis\android\trackercapture\fragments\programoverview\registerrelationshipdialogfragment\RegisterRelationshipDialogFragmentForm.java
Error:(4, 57) error: package org.hisp.dhis.android.sdk.ui.adapters.rows.events does not exist
Error:(14, 10) error: cannot find symbol class EventRow
Error:(25, 17) error: cannot find symbol class EventRow
Error:(29, 30) error: cannot find symbol class EventRow
Note: E:\TRackercapture\dhis2-android-trackercapture\app\src\main\java\org\hisp\dhis\android\trackercapture\fragments\programoverview\ProgramOverviewFragment.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Error:Execution failed for task ':app:compileDebugJava'.

> Compilation failed; see the compiler error output for details.
> Information:BUILD FAILED
> Information:Total time: 12.479 secs
> Information:102 errors
> Information:25 warnings
> Information:See complete output in console

**Comment by russnes** [comment]
Ok the same thing happened to me now that I checked. But I fixed it by Rebuilding the project.
Go to the top menu -> Build -> Rebuild Project.

See if that helps

**Comment by i-sourabh** [comment]
Yeah i did that also but still facing the same problem. Can you please tell me step by step from the beginning after downloading the zip files of SDK Master and Tracker capture .

**Comment by andy003** [comment]
and one more thing are we using any webservice at the server side for communication between the app and server ?

**Comment by russnes** [comment]
No just using the WepApi so no configuration is needed, except for setting up programs of course, and assigning to user and org unit assigned to user.

Can you show me a screen shot of your folder structure where you have the two directories? I haven't tested on Windows myself so I'm not sure if that is the issue..

Step by step:
- Download the two zips.
- Extract to the same root folder.
- Rename both directories, removing the "-master" part.
- Open Android Studio and import existing program -> trackercapture/build.gradle
- Rebuild project

**Comment by i-sourabh** [comment]
I have placed it in a single folder named Trackercapture in the E drive:
here it is:  I think R file is missing in the SDK as this one is the common error in every class.
import ......sdk.R;
![abc](https://cloud.githubusercontent.com/assets/9436345/9543081/84b6ab42-4d93-11e5-8713-fce702d95692.PNG)

**Comment by i-sourabh** [comment]
Following classes are missing in the SDK:  under events and fragments:
import org.hisp.dhis.android.sdk.utils.ui.adapters.rows.events.TrackedEntityInstanceColumnNamesRow;
import org.hisp.dhis.android.sdk.fragments.selectprogram.SelectProgramFragmentForm;

I think this code is the old one or something missing , can you please give me the latest updated code as per the app published on Playstore.?

**Comment by russnes** [comment]
Where are you seeing this error? Did you download the source code today?

**Comment by i-sourabh** [comment]
Yes i have downloaded the latest one from https://github.com/dhis2/dhis2-android-trackercapture

While compiling in the Android Studio when tried to run the app it gives these errors

**Comment by i-sourabh** [comment]
Thanks for your help till now, Is there any documentation on dhis2 SDK for android or any other tutorials for same which can help me to learn

**Comment by i-sourabh** [comment]
Now got the problem actually I am not able to import the files from the trackercapture like  I want to import the .R file and Event Row file but it does not comes up while typing the import command , only able to import SDK files.

when I moved the TrackedEntityInstanceColumnNamesRow.java to SDK it gives the .R error there also : 

import org.-----android.trackercapture.R;
import org----android.trackercapture.ui.rows.upcomingevents.EventRowType;

**Comment by i-sourabh** [comment]
Hi simernes, still there are lots of errors in the code to be resolved, can you please provide me the updated code .  Is the source code available at Launchpad unde DHIS Mobile Section? If so can you please give me the link?

**Comment by Madhuka** [comment]
I got same issue in dhis2-android-dashboard

**Comment by RajPratim21** [comment]
I also got the same issue

**Comment by erlingfjelstad** [comment]
Hi @RajPratim21 , have you read the README on how to set it up?
https://github.com/dhis2/dhis2-android-trackercapture/blob/2.23-legacy/README.md
